// export the data
export const data = [
  {
    id: 2,
    _id: "donut2",
    title: "Apple Krumb",
    description: "Apple flavored donut with cruncy sprinkles",
    price: 3.25,
    calories: "100 kCal",
    qty: 30,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/apple_krumb.jpg",
  },
  {
    id: 3,
    _id: "donut3",
    title: "Bavarian Kreme",
    description: "Donut with creamy filling",
    price: 3.65,
    calories: "200 kCal",
    qty: 20,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/bavarian_kreme.jpg",
  },
  {
    id: 4,
    _id: "donut4",
    title: "Blueberry",
    description: "Classic donut with blueberry flavor",
    price: 2.25,
    calories: "100 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/blueberry.jpg",
  },
  {
    id: 4,
    _id: "donut4",
    title: "Boston Kreme",
    description: "Donut with cream filling and chocolate glaze",
    price: 3.25,
    calories: "250 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/boston_kreme.jpg",
  },
  {
    id: 5,
    _id: "donut5",
    title: "Cinnamon Sugar",
    description: "Apple Donut with Cinnamon Glaze",
    price: 2.25,
    calories: "150 kCal",
    qty: 0,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/cinnamon_sugar.jpg",
  },
  {
    id: 6,
    _id: "donut6",
    title: "Old Fashioned",
    description: "Classic donut",
    price: 1.25,
    calories: "75 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/old_fashioned.jpg",
  },
  {
    id: 7,
    _id: "donut7",
    title: "Coconut",
    description: "Donut with Coconut Sprinkles",
    price: 2.25,
    calories: "150 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/coconut.jpg",
  },
  {
    id: 8,
    _id: "donut8",
    title: "Powdered Sugar",
    description: "Classic donut dusted with sugar",
    price: 1.25,
    calories: "120 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/powdered_sugar.jpg",
  },
  {
    id: 9,
    _id: "donut9",
    title: "Original Glaze",
    description: "Classic donut with simple glaze",
    price: 1.25,
    calories: "120 kCal",
    qty: 10,
    category: "normal",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/original_glaze.jpg",
  },
  {
    id: 10,
    _id: "donut10",
    title: "Sour Cream",
    description: "Classic donut with tangy sour cream glaze",
    price: 2.25,
    calories: "150 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/sour_cream.jpg",
  },
  {
    id: 11,
    _id: "donut11",
    title: "Vanilla Frosted",
    description: "Donut with vanilla frosting and sprinkles on top",
    price: 3.25,
    calories: "200 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/vanilla_frosted.jpg",
  },
  {
    id: 12,
    _id: "donut12",
    title: "Strawberry Frosted",
    description: "Donut with strawberry frosting and sprinkles",
    price: 3.25,
    calories: "200 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/strawberry_frosted.jpg",
  },
  {
    id: 13,
    _id: "donut13",
    title: "Marble Frosted",
    description: "Frosted donut with chocolate drizzle",
    price: 2.25,
    calories: "180 kCal",
    qty: 0,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/marble_frosted.jpg",
  },
  {
    id: 14,
    _id: "donut14",
    title: "Jelly",
    description: "Donut with jelly filling",
    price: 3.25,
    calories: "200 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/jelly.jpg",
  },
  {
    id: 15,
    _id: "donut15",
    title: "Chocolate Frosted",
    description: "Achocolypse now!",
    price: 3.25,
    calories: "250 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/chocolate_frosted.jpg",
  },
  {
    id: 16,
    _id: "donut16",
    title: "Chocolate Kreme",
    description: "Chocolate inside",
    price: 3.25,
    calories: "250 kCal",
    qty: 10,
    category: "featured",
    imageURL: "https://cmu-17-356.github.io/assets/images/donut_flavors/chocolate_kreme.jpg",
  },
];
