// import static image data.
import {
  donut1,
  donut2,
  donut3,
  donut4,
  donut5,
  donut6,
  donut7,
  donut8,
  donut9,
  donut10,
  donut11,
  donut12,
  donut13,
  donut14,
  donut15,
  donut16,
} from "../components/Assets";

// export the data
export const data = [
  {
    id: 2,
    _id: "donut2",
    title: "Choco Sprinkles",
    description: "Chocolate Donut with Sprinkles",
    price: 7.25,
    calories: 0.1,
    qty: 30,
    category: "normal",
    imageURL: donut1,
  },
  {
    id: 3,
    _id: "donut3",
    title: "Little Rainbow",
    description: "Donut with Sprinkles",
    price: 15.65,
    calories: 0.2,
    qty: 20,
    category: "normal",
    imageURL: donut2,
  },
  {
    id: 4,
    _id: "donut4",
    title: "Classic",
    description: "Glazed Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut3,
  },
  {
    id: 4,
    _id: "donut4",
    title: "Original",
    description: "Plain Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut4,
  },
  {
    id: 5,
    _id: "donut5",
    title: "Apple Cinnamon",
    description: "Apple Donut with Cinnamon Glaze",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut5,
  },
  {
    id: 6,
    _id: "donut6",
    title: "Birthday Special",
    description: "Birthday flavored donut with sprinkles",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut6,
  },
  {
    id: 7,
    _id: "donut7",
    title: "Tropical",
    description: "Donut with Coconut Sprinkles",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut7,
  },
  {
    id: 8,
    _id: "donut8",
    title: "Donut8",
    description: "Donut Donut Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut8,
  },
  {
    id: 9,
    _id: "donut9",
    title: "Donut9",
    description: "Donut Donut Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "normal",
    imageURL: donut9,
  },
  {
    id: 10,
    _id: "donut10",
    title: "Donut10",
    description: "We all love donuts",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut10,
  },
  {
    id: 11,
    _id: "donut11",
    title: "Donut11",
    description: "Donut Donut Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut11,
  },
  {
    id: 12,
    _id: "donut12",
    title: "Donut 12",
    description: "Krispy Kreme",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut12,
  },
  {
    id: 13,
    _id: "donut13",
    title: "Donut 13",
    description: "Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut13,
  },
  {
    id: 14,
    _id: "donut14",
    title: "Donut14",
    description: "Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut14,
  },
  {
    id: 15,
    _id: "donut15",
    title: "Donut 15",
    description: "Donut Donut Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut15,
  },
  {
    id: 16,
    _id: "donut16",
    title: "Donut 16",
    description: "Donut Donut Donut",
    price: 10.25,
    calories: 0.3,
    qty: 10,
    category: "featured",
    imageURL: donut16,
  },
];
