// import static image data.
import { donut1, donut2, donut3, donut4, donut5 } from "../components/Assets";

// export the data
export const data = [
  {
    id: 2,
    title: "fruit1",
    description: "Fresh Strawberries",
    price: "7.25",
    calories: "0.1",
    qty: "30",
    category: "fruits",
    imageURL: donut1,
  },
  {
    id: 3,
    title: "fruit2",
    description: "Mixed Kebab",
    price: "15.65",
    calories: "0.2",
    qty: "20",
    category: "fruits",
    imageURL: donut2,
  },
  {
    id: 4,
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "fruits",
    imageURL: donut3,
  },
  {
    id: 4,
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "fruits",
    imageURL: donut4,
  },
  {
    id: 4,
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "fruits",
    imageURL: donut5,
  },
  {
    id: 4,
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "fruits",
    imageURL: donut2,
  },
];
