// import static image data.
import {
  donut1,
  donut2,
  donut3,
  donut4,
  donut5,
  donut6,
  donut7,
  donut8,
  donut9,
  donut10,
  donut11,
  donut12,
  donut13,
  donut14,
  donut15,
  donut16,
} from "../components/Assets";

// export the data
export const data = [
  {
    id: 2,
    _id: "donut2",
    title: "fruit1",
    description: "Fresh Strawberries",
    price: "7.25",
    calories: "0.1",
    qty: "30",
    category: "normal",
    imageURL: donut1,
  },
  {
    id: 3,
    _id: "donut3",
    title: "fruit2",
    description: "Mixed Kebab",
    price: "15.65",
    calories: "0.2",
    qty: "20",
    category: "normal",
    imageURL: donut2,
  },
  {
    id: 4,
    _id: "donut4",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut3,
  },
  {
    id: 4,
    _id: "donut4",
    title: "fruit4",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut4,
  },
  {
    id: 5,
    _id: "donut5",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut5,
  },
  {
    id: 6,
    _id: "donut6",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut6,
  },
  {
    id: 7,
    _id: "donut7",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut7,
  },
  {
    id: 8,
    _id: "donut8",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut8,
  },
  {
    id: 9,
    _id: "donut9",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "normal",
    imageURL: donut9,
  },
  {
    id: 10,
    _id: "donut10",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut10,
  },
  {
    id: 11,
    _id: "donut11",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut11,
  },
  {
    id: 12,
    _id: "donut12",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut12,
  },
  {
    id: 13,
    _id: "donut13",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut13,
  },
  {
    id: 14,
    _id: "donut14",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut14,
  },
  {
    id: 15,
    _id: "donut15",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut15,
  },
  {
    id: 16,
    _id: "donut16",
    title: "fruit3",
    description: "Roasted Tilapia",
    price: "10.25",
    calories: "0.3",
    qty: "10",
    category: "featured",
    imageURL: donut16,
  },
];
