name: 'CI Checks'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  PR-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dependencies
        uses: fzwael/ncu-action@v1.3.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
