name: 'CI Checks'

on:
  push:
    branches:
      - main
  pull_request:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  PR-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dependencies
        uses: fzwael/ncu-action@v1.3.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
  Fly-Deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy app
    runs-on: ubuntu-latest
    needs: PR-Checks
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy